# Generated by Django 5.2.4 on 2025-07-23 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CandidaturaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=100)),
                ('idade', models.PositiveIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('resposta', models.TextField()),
                ('data_candidatura', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
